### ISSUE TITLE
Messed up text on default render

### ISSUE THREAD

**Issue by nprez** [MrTeferi/MTG-Proxyshop#11]
Latest version, default settings, templates all up to date.

When I try to render for example the default Berg Strider art that comes with the release, [this is how the card renders](https://user-images.githubusercontent.com/18358103/172668833-9518e6d0-a423-4a1b-85cf-8ee0599ecc4c.png).

This is running on Photoshop CC2015.

**Comment by MrTeferi** [comment]
Yeah I was pretty sure that would happen. Basically in the past we had to use a time consuming operation to check the bounds of a text layer, and we noticed that something changed either in a newer Photoshop or a newer Python API version that fixed text layer bounds so you no longer need to rasterize in order to get the correct bounds.

This confirms that it is indeed an update that happened somewhere between CC2015 and CC2021 (the one I use now). I'll just have to put in a version check at that step to use the old method on older versions of Photoshop. I would recommend updating Photoshop when you get the chance because post-2020 Photoshop has much better execution time, really handy!

I'll drop a hotfix version in a few minutes to correct the issue if you do decide to stick with the older Photoshop

**Comment by MrTeferi** [comment]
I just added the hotfix to release v1.1.3. Please read the note at the top of that release, another mistake was made and its important. You'll need to delete the `gauth.json` file from your Proxyshop/proxyshop directory, and also the file titled `version_tracker.json`. These were not supposed to be shipped with release and will mess up the Updater feature.

**Comment by nprez** [comment]
Still getting the same result on the latest hotfix. I deleted everything manually except for the templates folder and copied all the new stuff in. Then I re-updated each of the templates since it said they were out of date again.

I'll look into potentially updating Photoshop, though the last time I looked CC2015 was the latest version easily available through less than reputable means.

**Comment by MrTeferi** [comment]
If you haven't updated Photoshop yet, could you give the newest release a try? I updated the 1.1.3 release with a new file. You don't have to delete any files in your proxyshop directory just extract the contents into the folder and overwrite :)

**Comment by nprez** [comment]
No difference with the newest release.

**Comment by MrTeferi** [comment]
I just re-installed CC2015 and its working fine on my end with the latest release, same template, same image. Idk maybe Github didn't link you the new file for whatever reason?

That said, I did manage to find 2020, 2021, and 2022 versions of Photoshop on.. less reputable channels lol, shouldn't be too hard to find I'm sure you know where to look ;)

**Comment by nprez** [comment]
Yeah idk if it's not reproducible, I'll just look into upgrading and I'll mark this as closed.

Could still be some minor update difference or something even if we both have CC2015.
If you feel like looking into it further, the specific build is:
Adobe Photoshop Version: 2015.0.0 20150529.r.88 2015/05/29:23:59:59 CL 1024429  x64

But it's probably easy enough to just get a newer version.

**Comment by nprez** [comment]
Having downloaded Photoshop 2020, I can say I'm still getting the same issue unfortunately.

**Comment by MrTeferi** [comment]
Try the latest version 1.1.4, its safe to just overwrite your existing files with the new release. Also delete the folder called "datas" in the "proxyshop" folder if it exists there.

Also: in Photoshop go to Edit>Preferences>Units & Rulers, and make sure your Rulers units are set to "px" (pixels) and Type units set to "pt" (points), the app is supposed to set those for you but its possible Photoshop isn't giving the app permission to change those?

**Comment by nprez** [comment]
Now I get the error "PSD not found!" despite all of them being downloaded and up to date.

**Comment by nprez** [comment]
Also just as a quality of life thing, I tried deleting the templates and redownloading them using the built-in update button. If the "templates" folder or either of its 2 subfolders don't already exist, you'll run into an error.

**Comment by MrTeferi** [comment]
Are you by chance running Windows 11? Also, are there any special characters in your Proxyshop directory path? For example: C:/[MTG]/Proxyshop or anything like that? Some special characters such as brackets will screw up pathing. Also look in the "tmp" directory for a file called "error.txt", if there's any error logs in that folder please post them.

**Comment by nprez** [comment]
I'm running Windows 10 still.
The full path to proxyshop is: C:\Users\nick_\My Drive\MTG\MTG-Proxyshop

error.txt:
[06/15/2022 13:09] Line: 26
proxyshop\templates.py: (-2147352567, 'Exception occurred.', ('Illegal argument - argument 1\n- Required value is missing', 'Adobe Photoshop', None, 0, -2147220262))

If it matters, this is the version of photoshop 2020 I'm running: Adobe Photoshop Version: 21.2.2 20200807.r.289 2020/08/07: 287d0d87ec  x64
Note that photoshop itself opens, but then the Proxyshop window says it can't find the PSD.

**Comment by MrTeferi** [comment]
Oh another thing I just thought of: Proxyshop will probably not work if you have two versions of Photoshop installed, there doesn't seem to be any way around this atm as its a known issue with jsx scripts as well. Windows won't know which version of Photoshop to communicate the commands to and will cause some really bizarre behavior lol. Just thought I'd mention it in case you installed 2020 without uninstalling the older version

**Comment by nprez** [comment]
Doesn't seem to have made a difference.
![Only 2020 installed right now](https://user-images.githubusercontent.com/18358103/173898487-b6f88100-f86a-490c-880f-7ad65ca165d4.png)

**Comment by MrTeferi** [comment]
Could you post a screenshot of your proxyshop directory?

**Comment by MrTeferi** [comment]
Is the error message in /tmp/error.txt the same as before?

**Comment by nprez** [comment]
Yep:
![image](https://user-images.githubusercontent.com/18358103/173903903-627550c0-eacc-4859-95e7-a7fee7737eb6.png)

**Comment by MrTeferi** [comment]
Can you post a screenshot of your config.ini file?

**Comment by nprez** [comment]
![image](https://user-images.githubusercontent.com/18358103/173905347-ea949c67-79e3-49fb-925e-dd112135e9c0.png)

**Comment by nprez** [comment]
Reboot didn't help.

It's definitely possible there could be some issue with the installation. I'm going to be out for pretty much the rest of the day, but tomorrow I could try a different photoshop install.

**Comment by MrTeferi** [comment]
Yeah if you can try to get PS 2021+ and delete as much of the old Photoshop installation(s) as possible, maybe run a registry cleaner (I recommend CC Cleaner 👍). Definitely a very odd situation going on here, never seen anything like it my bet is the API is having trouble communicating with Photoshop for some reason. Maybe also check for any windows updates as well, since the API uses the windows RPC server/COM system to communicate with Photoshop so could be an issue related to that as well..

**Comment by nprez** [comment]
Happy to say after uninstalling photoshop, cleaning everything up, and reinstalling 2022, everything's working as expected :)
![image](https://user-images.githubusercontent.com/18358103/174088801-09970e8a-723a-4b8a-b8fd-77a201a1880b.png)
