### ISSUE TITLE
Toxrill, The Corrosive 

### ISSUE THREAD

**Issue by TheBigShow329** [MrTeferi/MTG-Proxyshop#12]
When trying to apply the Slime Counter trigger, I received the following:

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.51-V4-beta6 (build: 2022-06-24 13:26)
mage.abilities.effects.common.combat.GoadTargetEffect.apply(GoadTargetEffect.java:60)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:115)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1176)
mage.game.GameState.applyEffects(GameState.java:663)
mage.game.GameImpl.applyEffects(GameImpl.java:1747)
mage.game.GameState.processAction(GameState.java:652)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2009)
mage.game.GameImpl.playPriority(GameImpl.java:1513)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.EndPhase.playStep(EndPhase.java:47)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by MrTeferi** [comment]
I've got no idea what this is but it doesn't look like its related to Proxyshop, Proxyshop is not a java application. I think you're on the wrong repository.

**Comment by TheBigShow329** [comment]
I'm not sure what you mean. Also, I have not been able to duplicate this error message. I conceded, then I replayed the deck with no issues.

**Comment by MrTeferi** [comment]
What I mean is you're in the wrong Github repository, Proxyshop is not a game application its a photoshop scripting engine for generating MTG card images lol. This bug report belongs elsewhere
