### ISSUE TITLE
City of Traitors

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#13]
**Describe the bug**
Italicization in rules text where it shouldn't be.

**To Reproduce**
Details can be provided upon request.

**Your system:**
 - Python version: 3.9
 - Windows version: 11
 - Photoshop version: 2022 Latest.

**Screenshots**
![image](https://user-images.githubusercontent.com/102387379/178029666-e2979084-e7d1-480c-ab42-709eb2d09e18.png)

**Comment by MrTeferi** [comment]
Issue has been fixed as of next release!
