### ISSUE TITLE
Feature Request: Add config.ini option to enable/disable Legendary Crown

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#18]
It would be great if non-python users could have some option to disable the Legendary Crown. 

Particularly useful when rendering cards which don't originally have a crown, such the masterpiece.psd template, or really just any pre-Dominaria card.

**Comment by HelixVita** [comment]
For a particularly horrifying example of the kind of workaround the absence of this option requires on the part of the template creator, feel free to peruse https://github.com/HelixVita/FelixVita-Proxyshop-Plugins/commit/edc5d30c854cdc3be7f759c31cd4a447416684f0?diff=unified

Trigger warning / eye bleach / what will be seen cannot be unseen.

**Comment by MrTeferi** [comment]
This can already be configured at template level by specifying:
```python
self.is_legendary = False
```
during __init__ after super is called, and can also be specified as a property of your template subclass:
```python
@property
def is_legendary(self) -> bool:
    return False
```
