### ISSUE TITLE
Feature request: Add "feature request" issue template for GitHub Issues page on Proxyshop repo

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#19]
Currently the only issue template is "Bug Report".

Might be nice to have a go-to centralized place for people to make feature requests, rather than have all those ideas (both good and bad) float around the chat where they are easily lost or forgotten.

**Comment by HelixVita** [comment]
You could also set up a github action which adds a "Bug" label to bug issues and an "enhancement" label to feature requests.

**Comment by MrTeferi** [comment]
Done
