### ISSUE TITLE
Wrong set symbol

### ISSUE THREAD

**Issue by Engel666sk** [MrTeferi/MTG-Proxyshop#22]
**Describe the bug**
When i create a custom card and write the Setcode J20 the program won't use the right symbol.

**To Reproduce**
1. Fill out all the information
2. Type Setsymbol J20
3. Render Card

**Your system:**
 - Python version:3.10.6
 - Windows version: Windows 10, Version 21H2
 - Photoshop version: Photoshop CC 23.5

**Screenshots**

**Comment by MrTeferi** [comment]
Fixed
