### ISSUE TITLE
Bug: Could not save a copy as "Kongming, "Sleeping Dragon" ..." because the file name was not valid

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#23]
**Describe the bug**
See screenshot. I'm guessing the problem has to do with the `"` characters in the cardname.

**To Reproduce**
Attempt to render the card  `Kongming, "Sleeping Dragon"` with Proxyshop (any template).

**Your system:**
 - Python version: 3.8
 - Windows version: 11
 - Photoshop version: 23.5.0
 - Proxyshop version: v1.1.8

**Screenshots**
![image](https://user-images.githubusercontent.com/102387379/187019915-9f883d91-0ed8-4a4c-a6f4-a0e7df4b0c47.png)

**Comment by pozzum** [comment]
I can also confirm that the Circle of Protection cards do not automatically save because of the ":" character in the card name.

**Comment by MrTeferi** [comment]
This has been fixed for quite sometime by using a regex replace on special characters in the file name step! Thanks :)
