### ISSUE TITLE
Bug: [[Strategic Planning]] — When using bold rules text, the non-italicized part of the flavor is also bold

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#24]
**Describe the bug**
This one's a bit of an edge case, so prioritize accordingly.

**To Reproduce**
- Step 1: Enable bold font for rules text in the plugin's templates.py thus:
```
def __init__(self, layout):
    super().__init__(layout)
    con.font_rules_text = "MPlantin-Bold"
```
- Step 2: Render the PTK version of the card [[Strategic Planning]] (or presumably any card which has some non-italicized text in the flavor text)

**Your system:**
 - Python version: 3.8
 - Windows version: 11
 - Photoshop version: 23.5.0
 - Proxyshop version: v1.1.8

**Screenshots**
Intended effect on left. Proxyshop render on right.
![image](https://user-images.githubusercontent.com/102387379/187023877-0fde4ebf-21d9-4cc8-a4f7-bbf77ef51932.png)

**Comment by HelixVita** [comment]
Additional example
![image](https://user-images.githubusercontent.com/102387379/187036092-a9e6ea3b-7028-4821-bc16-db70ef1bac56.png)

**Comment by MrTeferi** [comment]
This feature has been added in v1.2.0, you can now pass `bold_rules_text` as True in the rules text layer object!
```python
self.text.append(
    text_classes.FormattedTextArea(
        layer = self.text_layer_rules,
        contents = self.layout.oracle_text,
        flavor = self.layout.flavor_text,
        reference = psd.getLayer(con.layers['TEXTBOX_REFERENCE'], self.text_layers),
        divider = psd.getLayer(con.layers['DIVIDER'], self.text_layers),
        centered = self.is_centered,
        rules_text_bold = True
    )
)
```
