### ISSUE TITLE
Feature request: The ability to adjust spacing between rules and flavor text

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#25]
Probably useful in general, but especially so as a way to fix the following issue:

![image](https://user-images.githubusercontent.com/102387379/187037865-119eba66-b990-407b-83b2-b597993ee2fb.png)

(When using the portal-style divider, the gap is not large enough, resulting in this unaesthetic smushed-together appearance).

Desired effect:
![image](https://user-images.githubusercontent.com/102387379/187038160-51cecd14-9003-4b57-8a74-b8124023de03.png)

**Comment by HelixVita** [comment]
I tried increasing the value of `flavor_text_lead_divider` in `constants.py`, but it seems to have no effect. 
![image](https://user-images.githubusercontent.com/102387379/189546404-13e3f04a-a350-4709-b6c3-46491dae85e5.png)

**Comment by MrTeferi** [comment]
As of 1.1.9 modifying con.flavor_text_lead_divider should be able to achieved the desired result :)
