### ISSUE TITLE
Feature request: The ability to add flavor bar even for cards with no rules text (only flavor text)

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#26]
There are 63 cards in Magic's history which meet this criterion.

Here they are: https://scryfall.com/search?q=-o%3A%2F.%2F+%28s%3Apor+or+s%3Ap02+or+s%3Aptk+or+s%3As99%29+-t%3Abasic

**Screenshots**
Intended appearance on left, Proxyshop render on right.
![image](https://user-images.githubusercontent.com/102387379/187040888-7e6674a4-7533-4b19-be17-80a039947433.png)

**Comment by HelixVita** [comment]
Scrolling thru all the cards on the scryfall search results page, it seems that they all have the divider in the exact same position.

![image](https://user-images.githubusercontent.com/102387379/187041362-2f0d96e8-7e30-4968-9d4e-ddce2fe79f68.png)

This means that one could probably implement a slightly "hacky" but much faster way. Roughly speaking:
1. Let `norulesbounds` be a new bounding box for rules text placement defined as the lower half of the normal bounding box
2. If card has flavor text AND card has no rules text, use `norulesbounds` instead of the normal bounding box
3. Unhide the flavor divider and place it always at the same x/y position (in the middle of the rules box)

**Comment by MrTeferi** [comment]
Yeah this seems outside the scope of Proxyshop's goals, I think something like this should be left to template makers, if I implement it at app level its not gonna turn out looking like the result you want anyways without some template level customizing lol
