### ISSUE TITLE
Bug: Long P&T text overflow

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#29]
**Describe the bug**
See screenshot. Should be self-explanatory.

**Screenshots**
![image](https://user-images.githubusercontent.com/102387379/189534249-100275d5-36c1-4994-be79-38fd419dfd37.png)

**Comment by MrTeferi** [comment]
I have a fix planned for this that will be implemented in the modular rewrite branch and rolled into release 1.2.0, this issue was actually the lightbulb moment for me that inspired the modular rewrite so I think it's befitting!

**Comment by MrTeferi** [comment]
This issue has now been addressed in 1.2.0
