### ISSUE TITLE
Alternate Language issue edge case

### ISSUE THREAD

**Issue by pozzum** [MrTeferi/MTG-Proxyshop#36]
**Describe the bug**
For alt language cards there is some code that doesn't work right for the Sega Dreamcast Cards

**To Reproduce**
try to render anything from this list https://scryfall.com/sets/psdg

**Fix**
I took a look at the error and the code and here is what's wrong;

/proxyshop/layouts.py
Starting line 71

`        # Alternate language?
        if scryfall['lang'] != "en":
            self.name_key = 'printed_name'
            self.oracle_key = 'printed_text'
            self.type_key = 'printed_type_line'
        else:
            self.name_key = 'name'
            self.oracle_key = 'oracle_text'
            self.type_key = 'type_line'`

For the Dreamcast cards (or any other alt language cards) it still uses "Name" "oracle_text" and "type_line" but doesn't include the "Printed" items in the json.
See theis from the Japanese STA card
https://api.scryfall.com/cards/e5e6d72d-ef92-46b2-853f-003ae6250d30?format=json&pretty=true

Adding an additional check in the if statement that the "Printed_Name" value exists in the JSON should fix this issue as a backup without breaking the intended function of feting alt language text.

**Comment by MrTeferi** [comment]
@pozzum Thanks for the heads up, I just pushed a change that patches this issue!
