### ISSUE TITLE
German Keyboard problems.

### ISSUE THREAD

**Issue by Engel666sk** [MrTeferi/MTG-Proxyshop#39]
**Describe the bug**
Whenever i render a card with apostrohopes or quotation marks, Proxyshop always imports the right text from scryfall, but then changes it to german symbols. I changed my system language to english, tried various keyboard layouts, but nothing seems to work.

**To Reproduce**
I don' know if you can reproduce that behaviour.

**Your system:**
 - Python version: 3.10
 - Windows version:Version	10.0.19044 Build 19044
 - Photoshop version: Most recent in Creative Cloud

**Screenshots**

https://user-images.githubusercontent.com/111659540/196001659-ea9f6dd9-878e-43a4-85ec-3abced3f3b8e.mp4

**Comment by MrTeferi** [comment]
Issue has been fixed with Force.English.Formatting in config.ini
