### ISSUE TITLE
Template maintenance: Add support for Prototype (new ability in BRO)

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#41]
This could probably just be made a part of normal.psd, right?

![B544B657-7E60-4A11-91EE-8C40A3F9F298](https://user-images.githubusercontent.com/102387379/199164039-7d7d88f8-5995-4c92-a1b2-94be3aa2a94b.jpeg)

**Comment by MrTeferi** [comment]
This is most likely going to get its own template subclass like Mutate cards

**Comment by MrTeferi** [comment]
Prototypes are now supported! Closing this :)
