### ISSUE TITLE
[FEATURE] - Allow hiding set symbol and/or collector's information

### ISSUE THREAD

**Issue by lukegothic** [MrTeferi/MTG-Proxyshop#49]
**Is your feature request related to a problem? Please describe.**
I have edited a template so that the set symbol and collector's information layers are hidden, but those changes aren't honored by Proxyshop because they are always put on visible.

**Describe the solution you'd like**
I want to be able to hide non-essential parts of a template. 
Main solution should be proxyshop honoring layer configuration of the template.
If it is not possible, either having a button on the main program, or being able to change a setting inside the config.ini that you can change to show / hide set symbol and/or collector's information.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by MrTeferi** [comment]
Well you can disable auto set symbol and replace default set symbol with a blank space in config.ini, or just change the opacity of the layer to 0. You can also use 0 opacity on the collector info layers as well.

**Comment by HelixVita** [comment]
> Well you can disable auto set symbol and replace default set symbol with a blank space in config.ini, or just change the opacity of the layer to 0. You can also use 0 opacity on the collector info layers as well.

@MrTeferi FTFY
https://github.com/MrTeferi/MTG-Proxyshop/pull/50
