### ISSUE TITLE
[BUG] - Banned cards due to non-appropiate imagery aren't found by new scryfall search method

### ISSUE THREAD

**Issue by lukegothic** [MrTeferi/MTG-Proxyshop#52]
**Describe the bug**
The cards on the following list https://tagger.scryfall.com/tags/card/banned-due-to-racist-imagery aren't found by the new scryfall search method. Works on 1.1.8.

**To Reproduce**
1. Put an image for each of the card names on the list inside the art folder
2. Open proxyshop and render all

**Your system:**
 - Python version: 3.10.4
 - Windows version: 10
 - Photoshop version: 2021
 - Proxyshop version: 1.1.9

**Screenshots**
![image](https://user-images.githubusercontent.com/3224037/201026794-31deb194-9889-44fa-9383-35d4233c4e7f.png)
![image](https://user-images.githubusercontent.com/3224037/201026645-bf8acd59-dd5d-4062-9c96-f285e10daa86.png)

**Comment by lmancini** [comment]
@lukegothic do you have a chance to try the current `main` branch? I'm on it and these works correctly. @MrTeferi did some modifications to Scryfall search between 1.1.9 and current `main`, so realistically your issue was fixed as a side effect of them.

**Comment by MrTeferi** [comment]
These cards worked in 1.1.8 and also work in on the python version presently (are fixed for 1.2.0)
