### ISSUE TITLE
[BUG] - Kivy not (yet) working with Python 3.11

### ISSUE THREAD

**Issue by davidianstyle** [MrTeferi/MTG-Proxyshop#57]
**Describe the bug**
This seems to be a[ known issue](https://github.com/kivy/kivy/issues/8042)
![Python 3 11 Install Error](https://user-images.githubusercontent.com/6446624/203392768-00bed05e-0df1-4804-a04d-9e6a7693aea4.png)
Logging this issue in case the workaround described below helps anyone get their setup working. The developers of [kivy](https://github.com/kivy/kivy/) have acknowledged this issue 10 days ago and are working on a fix.

**To Reproduce**
1. Make sure you're running Python 3.11:
```
$ python --version
Python 3.11.0
```
2. Run  `$ python -m pip install -r requirements.txt`
```
Defaulting to user installation because normal site-packages is not writeable
Collecting photoshop-python-api
  Using cached photoshop_python_api-0.19.7-py3-none-any.whl (64 kB)
Collecting Kivy~=2.1.0
  Using cached Kivy-2.1.0.tar.gz (23.8 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Collecting setuptools
        Using cached setuptools-65.6.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting cython!=0.27,!=0.27.2,<=0.29.28,>=0.24
        Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
      Collecting kivy_deps.gstreamer_dev~=0.3.3
        Using cached kivy_deps.gstreamer_dev-0.3.3-cp311-cp311-win_amd64.whl (3.9 MB)
      ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2_dev~=0.4.5 (from versions: 0.5.1)
      ERROR: No matching distribution found for kivy_deps.sdl2_dev~=0.4.5
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Workaround:**
Luckily, there seems to be a temporary workaround to allow use of Python 3.11:
```
python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/
python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/
```
Also need to manually install remaining requirements:
1. Remove `Kivy` and `asynckivy` from `requirements.txt`
2. Save local changes
3. Install remaining requirements
```
python -m pip install -r requirements.txt
```

**Your system:**
 - Python version: 3.11.0
 - Windows version: Microsoft Windows 10 Pro (Version 10.0.19045 Build 19045)
 - Photoshop version: Photoshop 2023 (Version 24.0.1)

**Comment by davidianstyle** [comment]
One more step for workaround (must install Photoshop module):
`python -m pip install photoshop_python_api`

**Comment by MrTeferi** [comment]
I would amend those recommendations just a bit, asynckivy I believe supports 3.11 (and isn't a main dependency of Kivy, its a separate module to help do asynchronous operations with the kivy gui) so I THINK you can just leave asynckivy in the requirements.txt

In any case I'm gonna be making a commit soon to transition us over to poetry for managing dependencies which should be able to trivially account for things like this 👍

**Comment by gizix** [comment]
> **Workaround:** Luckily, there seems to be a temporary workaround to allow use of Python 3.11:
> 
> ```
> python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/
> python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/
> ```
> 
> Also need to manually install remaining requirements:
> 
> 1. Remove `Kivy` ~~and `asynckivy`~~ from `requirements.txt`
> 2. Save local changes
> 3. Install remaining requirements
> 
> ```
> python -m pip install -r requirements.txt
> ```

As @MrTeferi mentioned, its okay to leave asynckivy in there if you have it.  This worked brilliantly and my project is running with my 3.11 virtual environment.  Thank you @davidianstyle !

**Comment by MrTeferi** [comment]
Now that we use poetry to manage dependencies, I've updated the kivy dependency to use the latest dev package which does work with Python 3.11.X! Will mark this resolved for now
