### ISSUE TITLE
[BUG] - New scryfall search includes art cards on the search results and those aren't valid to render

### ISSUE THREAD

**Issue by lukegothic** [MrTeferi/MTG-Proxyshop#58]
**Describe the bug**
Scryfall search is including art cards on the search results and this makes proxyshop discard the search result and throw a "Layout incompatible" error.

**To Reproduce**
1. Open config.ini and set Scryfall.Ascending = True
2. Put a file called "Prismatic Vista" in the art folder
3. Press render
4. It says "Layout incompatible"

**Your system:**
 - Python version: 3.10.4
 - Windows version: W10
 - Photoshop version: 2021
 - Proxyshop version: 1.1.9

**Screenshots**
![image](https://user-images.githubusercontent.com/3224037/205729663-a2c3b2d5-bbf4-424a-8119-cbc2ab4a0759.png)

**Comment by MrTeferi** [comment]
I've added a fix to this issue on my end and seems to be working, will be pushing some more commits tonight. I think 1.2.0 will be dropping before the end of the week! Just need to run deep tests now, otherwise it's complete

**Comment by lukegothic** [comment]
Awesome :)

**Comment by MrTeferi** [comment]
My thoughts exactly! While I was at it I also fixed a bug with special characters in card name, had to use urllib.parse.quote to feed the name to the scryfall url. Example card is "+2 Mace" which wasn't working before, but will work after this fix :)

**Comment by MrTeferi** [comment]
> Awesome :) any scryfall object that has "set_type": "memorabilia" should be excluded imho.
> 
> Also, I guess any result which layout property looks fishy (eg: art_series) should be excluded too.
> 
> List of layouts: ['adventure', 'art_series', 'augment', 'class', 'double_faced_token', 'emblem', 'flip', 'host', 'leveler', 'meld', 'modal_dfc', 'normal', 'planar', 'reversible_card', 'saga', 'scheme', 'split', 'token', 'transform', 'vanguard']

Fix has been pushed! Cheers!
