### ISSUE TITLE
[BUG] - Discord invitation link on README.MD expired

### ISSUE THREAD

**Issue by lukegothic** [MrTeferi/MTG-Proxyshop#59]
**Describe the bug**
Discord invitation link on README.MD expired

**Comment by MrTeferi** [comment]
> **Describe the bug** Discord invitation link on README.MD expired

Has already been fixed, unfortunately Discord pulled our permalink again and we're waiting on another boost to get it back. You can join here:
https://discord.gg/magic-proxies-889831317066358815

Also please drop a server boost if you got one lying around ;D
