### ISSUE TITLE
Windows 11 says the executable is a virus.

### ISSUE THREAD

**Issue by richterlevania3** [MrTeferi/MTG-Proxyshop#69]
That's it.

The name of the virus is Trojan:Win32/Sabsik.EN.D!ml

**Comment by MrTeferi** [comment]
False positive, will be fixed in 1.6.0 thanks.

**Comment by MrTeferi** [comment]
Probably fixed in 1.6.0, have tested on machines that had similar issues. If it isn't fixed, there probably isn't much we can do other than pay for code signing (which probably won't be a priority any time soon since it costs money lol)
