### ISSUE TITLE
Basic lands don't work

### ISSUE THREAD

**Issue by myojin223** [MrTeferi/MTG-Proxyshop#7]
**Describe the bug**
When trying to render basic lands, they open the template and just stop, no errors or failures but nothing more happens.

**To Reproduce**
1. I put art in the art folder named it after a land and opened up the Proxyshop GUI and selected the basic land tab and clicked render all. Also tried render target which had the same effect.
2. I also tried deleting the basic land names out of the constants.py file. With the old Autoproxy doing this would let you make basic lands with any template, however in this case, it still only opens the default basic template and stops. 
3. After doing this I cleared the py_cache folder where the constants.py is located but had no luck with that either.

**Your system:**
 - Python version: 3.9.12
 - Windows version: Win 10 (latest I think)
 - Photoshop version: 23.3.1 20220419.r.426
![2022-05-07 20_37_20-](https://user-images.githubusercontent.com/64243555/167279392-ceb85780-ad38-44b0-8c96-d7d3a65eaa53.png)

**Screenshots**

**Comment by MrTeferi** [comment]
This big is fixed as of release 1.1.2, commit pending!
