### ISSUE TITLE
MDFC cards not working

### ISSUE THREAD

**Issue by preshtildeath** [MrTeferi/MTG-Proxyshop#8]
**Describe the bug**
MDFC card will load scryfall data, then gives "Layout 'modal_dfc' not supported!" error in console.
error.txt: select_frame_layers() missing 1 required positional argument: 'color_indicator'

**To Reproduce**
Open Proxyshop, select MDFC tab, select Normal, then Render Target. Selected file named "Needleverge Pathway (Piotr Dura) [ZNR].png"

**Your system:**
 - Python version: 3.10.3
 - Windows version: Version	10.0.19043 Build 19043
 - Photoshop version: Adobe Photoshop Version: 21.2.3 20200902.r.308 2020/09/02: 4ea4dadce6  x64

**Screenshots**
![image](https://user-images.githubusercontent.com/103437609/167308646-f9786d5b-913f-44b1-a33c-ea7fca078686.png)

**Comment by MrTeferi** [comment]
Fixed as of upcoming release 1.1.2, commit pending, thanks!
